### ISSUE TITLE
Import Requests Directly instead of using Vendored

### ISSUE THREAD

**Issue by adawalli** [aws-cloudformation/custom-resource-helper#16]
Would you consider adding requests to your requirements instead of importing from botocore?

The following Warning has started to pop up when invoking crhelper

`/var/task/botocore/vendored/requests/api.py:67: DeprecationWarning: You are using the put() function from 'botocore.vendored.requests'.  This is not a public API in botocore and will be removed in the future. Additionally, this version of requests is out of date.  We recommend you install the requests package, 'import requests' directly, and use the requests.put() function instead.
  DeprecationWarning`

**Comment by tjstansell** [comment]
Looks like this should be closed since the PR was merged.
