### ISSUE TITLE
Possible reasons for logs not appearing on Delete call?

### ISSUE THREAD

**Issue by thvasilo** [aws-cloudformation/custom-resource-helper#44]
I have a particular example were logs are not generated when delete is called, but they are on Create.

I tried looking into the particulars about how the `sleep_on_delete` parameter is handled, but I'm a bit confused. Could you explain how [line 87](https://github.com/aws-cloudformation/custom-resource-helper/blob/master/crhelper/resource_helper.py#L87) in the resource_helper achieves the requested wait time?

EDIT: More context

After debugging a bit here's the behavior I'm observing:

We're using custom resources to clean up AWS resources on CFN delete. For example, we empty S3 buckets, then delete them, because CFN fails to delete non-empty buckets.

Our CFN _conditionally_ launches some resources that take a long time to spin up and delete (SageMaker notebook instances) (~5 min to create and delete).

When I launch the CFN with the condition set to true, the SageMaker notebook instance is created, and when deleting the stack, the cleanup function finishes and logs its output to CloudWatch as expected, as the stack takes ~5 minutes to delete.

When I launch with the condition set to false, the "slow" resource is not created, so the deletion of the stack is very fast. As a result, it seems like my cleanup function is not done by the time the custom resource lambda function starts getting deleted itself. There are no logs of the Delete call on CloudWatch, and the custom resource fails to delete with the error 

> Failed to delete resource. An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied

**Comment by jaymccon** [comment]
Late to respond, but in case it's still of use....

https://github.com/aws-cloudformation/custom-resource-helper/blob/main/crhelper/resource_helper.py#L99-L107 attempts to wait 15 seconds less than the remaining lambda execution time before responding, to give cwl as much time as possible to receive logs before the lambda is deleted (which stops further logs from arriving). 

So if a lambda function execution has 20 seconds left, the function will wait 5 seconds before returning a response to cfn. Increasing the lambda timeout to around 2 minutes more than how long your code takes to execute should be enough to ensure that delete logs all arrive.

**Comment by thvasilo** [comment]
Turns out our dependency structure was not correct, leading to a policy being deleted before the Lambda resource, which broke the delete operation. After fixing this deletion and logging works as expected.
