### ISSUE TITLE
Add warning that this framework is incompatible with the AWS CDK custom resource framework

### ISSUE THREAD

**Issue by phitoduck** [aws-cloudformation/custom-resource-helper#65]
Hi there,

Would it be possible to add a warning to the README for confused folks like me saying that `crhelper` is NOT to be used with AWS CDK custom resources?

I wasted several hours today debugging a custom resource created using the `aws_cdk.custom_resources.Provider` framework. The lambda handler in question was using the `crhelper` framework, but I learned that `crhelper` was not intended to be used with AWS CDK in this manner.

Two incompatibilities I discovered with `crhelper` and the CDK custom resource framework:

- `crhelper` wraps your code with a global `try/except` block. This means that your lambda handler cannot raise exceptions that cause the handler to exit. This is problematic with the CDK framework because raising such exceptions is the only mechanism for causing a resource to fail creation, deletion, etc. with the CDK framework.

- `crhelper` emits an HTTP request to inform CloudFormation of the payload with attributes such as `Data`, `PhysicalResourceId`, etc. This, also, is not compatible with the CDK framework--which instead requires these values to be the returned values of the lambda handler.

Since I struggled with this, I wonder if others will too.

**Comment by calebpalmer** [comment]
Thank you for this.  I wasted hours trying to figure out why my Data was not making it back to the custom resource.  +1 for adding a note in the README for this!

**Comment by iamchadarmstrong** [comment]
Also in the same boat. Wasted a lot of time.

**Comment by eze1981** [comment]
Same here. What I found is that a lambda function with the crhelp works only when you don't use the Provider and instead you pass the arn to the ServiceToken. 

Following [this example](https://aws.amazon.com/blogs/infrastructure-and-automation/aws-cloudformation-custom-resource-creation-with-python-aws-lambda-and-crhelper/), the custom resource will be: 

```typescript
const crhelperSumResource = new lambda.Function(...);

...

const customResource = new CustomResource(this, 'MyCustomResource', {
      serviceToken: crhelperSumResource.functionArn,
      properties: {
        'No1': 1,
        'No2': 2
      },
    });
```

**Comment by awsjpleger** [comment]
Failed in the same trap. took 2 days of my life. Thanks for letting us know!

For CDK v2 users, as mentioned above by **eze1981**:  Just do not use the custom_resources.Provider class at all, and use your crhelper lambda function ARN as the serviceToken parameter of the CustomResource class.

**Comment by mccauleyp** [comment]
Same boat, thanks to the commenters here for saving me what additional time I would've puzzled over this!

**Comment by iainelder** [comment]
All here, I'm just curious, where did you learn about the custom resource helper?

This repo doesn't seem to get much attention from its owner. So maybe those sources should be updated to warn about it.

I think I discovered crhelper via the CloudFormation documentation. I'm sure it was there once, but I can no longer find it via search. The only remaining references [shown by a search](https://docs.aws.amazon.com/search/doc-search.html?searchPath=documentation&searchQuery=crhelper) are from Amazon Sagemaker and AWS Prescriptive Guidance.

That suggests to me that the CloudFormation team would rather we don't use this at all :-)

**Comment by mccauleyp** [comment]
> All here, I'm just curious, where did you learn about the custom resource helper?

I got here from a link in the AWS Lambda Powertools sidebar: https://awslabs.github.io/aws-lambda-powertools-python/2.13.0/

Seems like the Powertools libraries for other languages, at least for Java, have Custom Resources features built-in but the Python one links out to here.
