### ISSUE TITLE
Always get "Unable to marshal response" Error?

### ISSUE THREAD

**Issue by alanktso** [aws-cloudformation/custom-resource-helper#68]
I have followed the example to write some codes that create custom resources in Lambda for Cloudformation.  However, it seems that it always trigger "Unable to marshal response" Error:

[ERROR] Runtime.MarshalError: Unable to marshal response: Object of type set is not JSON serializable
Traceback (most recent call last):

I cannot searched anyone else meeting this issue.  I am still not sure whether it was caused by my setup or not.  For some cases, I can simply ignore this.  But for some other cases, it seems to trigger the lambda to retry a few times.  I know that my functions should be idempotent but sometimes it may not be so practical.  My current workaround is to set MaximumRetryAttempts to zero but I don't think it is a good solution.

**Comment by iainelder** [comment]
This appears to be a Python programming error.

I get a very similar message when trying to serialize a set object using the stock JSON library.

When I try to serialize a dict, list, str or integer I get a JSON value.

```pycon
>>> import json
>>> json.dumps(set())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: set([]) is not JSON serializable
>>> json.dumps({})
'{}'
>>> json.dumps([])
'[]'
>>> json.dumps("str")
'"str"'
>>> json.dumps(123)
'123'
```

JSON has no concept of a set. Whatever you are returning from your function, try to represent it as a type that can be serialized.

**Comment by alanktso** [comment]
My code simply return a physical resource id which is a string. But I am not sure what will return by the helper. I really don't understand why a set was returned and the error appear at the end of the lambda log.

**Comment by iainelder** [comment]
Can you share a reproducible example here? When we have code that we can read and run either I or someone else here might be able to help dig into it.

**Comment by alanktso** [comment]
Thanks for the hint.  After testing with some sample codes & my codes, I can conclude the following codes caused the issues:

```
def lambda_handler(event, context):
  return {
  helper(event, context)
  }
```

The curly braces make the returned value of helper become a set.  Fixed after changing to parenthesis.  Thanks again.

**Comment by iainelder** [comment]
Yup, that syntax would return a set with one element, the helper function's return value.

Glad to see you found and fixed the problem. Happy to help!
