### ISSUE TITLE
How to handle when resource fail to update?

### ISSUE THREAD

**Issue by thoithoi58** [aws-cloudformation/custom-resource-helper#70]
Hi, I'm currently have a update stack as follow
```
@helper.update
def update(event, context):
    try:
        physical_id = event['PhysicalResourceId']
        request_type = event['RequestType']
        properties = event['ResourceProperties']
        old_properties = event['OldResourceProperties']

        # do something here
       create_repository()
       ....
       set_default_reviewer()       <------ this is where it fail when I input invalid user
       # end

        return physical_id

    except Exception as err:
        helper.Status = 'FAILED'
        helper.Reason = err
        return physical_id
```

However when the stack fail, it stuck in the `UPDATE_ROLLBACK_FAILED` state, I want the stack to be in `UPDATE_ROLLBACK_COMPLETE`. Am i doing wrong? Please help me

Thanks

**Comment by thoithoi58** [comment]
Update: Instead of set the status as `FAILED` and `Reason`. I used the `helper.init_failure()` method but it show `UPDATE_COMPLETE` so not helpful much

**Comment by thoithoi58** [comment]
Hi sir @iainelder, sorry to bother you. But I see you are very actively in this repo. 

I read some of your comment and advices such as set the PhysicalID or init_failure to signal cloudformation as the update method is fail. But none of them is seem to work for me

Can you help me?

Sorry again for bother you.

**Comment by iainelder** [comment]
Hi, no problem. I do my best to help others who are using this module.

I'm not using it in my current project and so my knowledge may be out of date or incomplete.

I understand that you say your code can fail in the set_default_reviewer function. When it fails, you want the stack to end up in a UPDATE_ROLLBACK_COMPLETE status, but instead you see an UPDATE_ROLLBACK_FAILED status.

Did I understand it correctly?

**Comment by thoithoi58** [comment]
Hi sir, thanks for replying me.

I'm actually firguring out the solution, turn out when Cloudformation try to rollback, my `set_default_viewer` function attemp to delete the fail properties that was fed in, but it also failed as I was trying to delete a properties which does not exist, hence that's why it stuck on `UPDATE_ROLLBACK_FAILED`

Thanks again sir for your time for helping me, I'm closing this case.

Hope you're doing well
