### ISSUE TITLE
How to know current request is ROLLBACK type?

### ISSUE THREAD

**Issue by thoithoi58** [aws-cloudformation/custom-resource-helper#71]
Hi,

I have some code that need to behave different when the request is update and rollback. But according to AWS document, the rollback request is just a update one with new properties and old one in reverse, there's nothing to distinguish between those two. Anyone have any idea to archive it?

Thanks.

**Comment by iainelder** [comment]
The only thing that comes to mind just now would be to use the CloudFormation API to check the latest stack events to determine the context of the update.

Why do need to distinguish between a "forward" update and a "backward" update (rollback)?
