### ISSUE TITLE
Handling incorrect parameters

### ISSUE THREAD

**Issue by alexjurkiewicz** [aws-cloudformation/custom-resource-helper#9]
hi, thanks for the project!

It's not clear to me how to handle raising errors during create/update when user provided properties are incorrect. Do I raise an exception? Or do I set `helper.Status` to `FAILED` myself?

**Comment by igreg** [comment]
It is somewhat connected the issue #7 that I am having for this exact reason. I am letting boto3 raise exception as most of the time the error message is explicit enough to be used as a reason. Unfortunately this module will return a `PhysicalResourceId` even if none got created so you'll have to cater for this if your `delete` function is expecting `event['PhysicalResourceId']` to be a valid ARN.

**Comment by jaymccon** [comment]
Raising an exception is the easiest way to go, traceback will be logged in CloudWatch logs and the error message sent back to CloudFormation.

**Comment by mlda065** [comment]
Can you please update the README to make it clear that an exception is the correct way to throw an error?

**Comment by jaymccon** [comment]
@mlda065 07231f4

**Comment by mlda065** [comment]
thanks
